<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Add to cart_inventory_item_img</name>
   <tag></tag>
   <elementGuidId>57ac9c55-0126-4b28-bc37-bbb76c0129d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='item_1_img_link']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#item_1_img_link > img.inventory_item_img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e5e2656a-d75b-4bef-bfc8-9b2a73d17c04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Sauce Labs Bolt T-Shirt</value>
      <webElementGuid>a993c5ef-6ccb-4fa2-84a8-339b4b4e75f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inventory_item_img</value>
      <webElementGuid>c7837778-7e81-4271-bbc7-611179d16260</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/bolt-shirt-1200x1500.c2599ac5.jpg</value>
      <webElementGuid>3edf0992-3cdf-4e1e-97c8-e0695d0c6b78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;item_1_img_link&quot;)/img[@class=&quot;inventory_item_img&quot;]</value>
      <webElementGuid>e3b399b4-27d0-4f8b-9d71-40a37b7d1c1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='item_1_img_link']/img</value>
      <webElementGuid>fc2e1f0c-2e8f-4345-b21f-a93763e184aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Sauce Labs Bolt T-Shirt']</value>
      <webElementGuid>7b73f7b6-31c3-488b-b6f3-3aefca3bb8fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/a/img</value>
      <webElementGuid>14168f5f-d4a6-4415-bf64-13e6cc9e8169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Sauce Labs Bolt T-Shirt' and @src = '/static/media/bolt-shirt-1200x1500.c2599ac5.jpg']</value>
      <webElementGuid>6161aca4-eb00-4f87-9252-d84a61232296</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
